version: '3.5'
services:
  peercoind:
    image: peercoin/peercoind
    restart: on-failure:20
    ports:
     - "9901:9904"
    environment:
       - RPC_USER=peercoind
       - RPC_PASSWORD=peercoindrpc
       - TESTNET=1
       - TXINDEX=1
       - WALLETNOTIFY/usr/local/bin/walletnotify.sh %s
    volumes:
      - /opt/go-peerassets/peercoin/:/data
    command:
      -nominting
      -rpcallowip=0.0.0.0/0
      -testnet
      -txindex
  go-peerassets:
    restart: always
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - peercoind
    environment:
      - RPC_HOST=peercoind
      - RPC_PORT=9904
      - RPC_USERNAME=peercoind
      - RPC_PASSWORD=peercoindrpc
